/** Stable error codes exposed by the Safety module. */
export const SafetyErrors = {
  SELF_ACTION_FORBIDDEN: 'SAFETY_SELF_ACTION_FORBIDDEN',
  BLOCK_NOT_FOUND: 'SAFETY_BLOCK_NOT_FOUND',
  INTERACTION_BLOCKED: 'SAFETY_INTERACTION_BLOCKED',
  IDEMPOTENCY_KEY_MISSING: 'SAFETY_IDEMPOTENCY_KEY_MISSING',
  IDEMPOTENCY_KEY_INVALID: 'SAFETY_IDEMPOTENCY_KEY_INVALID',
  IDEMPOTENCY_CONFLICT: 'SAFETY_IDEMPOTENCY_CONFLICT',
  REPORT_RATE_LIMITED: 'SAFETY_REPORT_RATE_LIMITED',
  EVIDENCE_INVALID: 'SAFETY_EVIDENCE_INVALID',
  BATCH_TOO_LARGE: 'SAFETY_BATCH_TOO_LARGE',
} as const;
