/** Mã lỗi của Auth module (docs/05 § 5.5). */
export const AuthErrors = {
  PHONE_OTP_DISABLED: 'AUTH_PHONE_OTP_DISABLED',
  OTP_INVALID: 'AUTH_OTP_INVALID',
  OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  OTP_TOO_MANY_ATTEMPTS: 'AUTH_OTP_TOO_MANY_ATTEMPTS',
  OTP_REQUEST_RATE_LIMITED: 'AUTH_OTP_REQUEST_RATE_LIMITED',
  REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_REUSED: 'AUTH_REFRESH_TOKEN_REUSED',
  SOCIAL_TOKEN_INVALID: 'AUTH_SOCIAL_TOKEN_INVALID',
  SOCIAL_PROVIDER_NOT_SUPPORTED: 'AUTH_SOCIAL_PROVIDER_NOT_SUPPORTED',
  IDENTITY_ALREADY_LINKED: 'AUTH_IDENTITY_ALREADY_LINKED',
  GUEST_DEVICE_TOKEN_INVALID: 'AUTH_GUEST_DEVICE_TOKEN_INVALID',
  GUEST_IDENTITY_RETIRED: 'AUTH_GUEST_IDENTITY_RETIRED',
  GUEST_UPGRADE_NOT_ALLOWED: 'AUTH_GUEST_UPGRADE_NOT_ALLOWED',
  USER_BANNED: 'AUTH_USER_BANNED',
} as const;
