/** Mã lỗi của Auth module (docs/05 § 5.5). */
export const AuthErrors = {
  PHONE_OTP_DISABLED: 'AUTH_PHONE_OTP_DISABLED',
  OTP_INVALID: 'AUTH_OTP_INVALID',
  OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  OTP_TOO_MANY_ATTEMPTS: 'AUTH_OTP_TOO_MANY_ATTEMPTS',
  OTP_REQUEST_RATE_LIMITED: 'AUTH_OTP_REQUEST_RATE_LIMITED',
  REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_REUSED: 'AUTH_REFRESH_TOKEN_REUSED',
  SOCIAL_TOKEN_INVALID: 'AUTH_SOCIAL_TOKEN_INVALID',
  SOCIAL_PROVIDER_NOT_SUPPORTED: 'AUTH_SOCIAL_PROVIDER_NOT_SUPPORTED',
  USER_BANNED: 'AUTH_USER_BANNED',
} as const;
