export const MediaErrors = {
  GUEST_FORBIDDEN: 'MEDIA_GUEST_FORBIDDEN',
  INVALID_CONTENT_TYPE: 'MEDIA_INVALID_CONTENT_TYPE',
  FILE_TOO_LARGE: 'MEDIA_FILE_TOO_LARGE',
  ASSET_NOT_FOUND: 'MEDIA_ASSET_NOT_FOUND',
  ASSET_NOT_READY: 'MEDIA_ASSET_NOT_READY',
} as const;
