/** Mã lỗi của Economy module (docs/05 § 5.5). */
export const EconomyErrors = {
  WALLET_INSUFFICIENT_BALANCE: 'ECONOMY_WALLET_INSUFFICIENT_BALANCE',
  IDEMPOTENCY_KEY_MISSING: 'ECONOMY_TRANSACTION_IDEMPOTENCY_KEY_MISSING',
  IDEMPOTENCY_CONFLICT: 'ECONOMY_TRANSACTION_IDEMPOTENCY_CONFLICT',
  TRANSACTION_NOT_FOUND: 'ECONOMY_TRANSACTION_NOT_FOUND',
  TRANSACTION_ALREADY_REVERSED: 'ECONOMY_TRANSACTION_ALREADY_REVERSED',
  IAP_RECEIPT_INVALID: 'ECONOMY_IAP_RECEIPT_INVALID',
  IAP_PRODUCT_UNKNOWN: 'ECONOMY_IAP_PRODUCT_UNKNOWN',
  VIP_PLAN_UNKNOWN: 'ECONOMY_VIP_PLAN_UNKNOWN',
} as const;
