/** Mã lỗi của Discovery module (docs/05 § 5.5). */
export const DiscoveryErrors = {
  CURSOR_INVALID: 'DISCOVERY_CURSOR_INVALID',
  FILTER_INVALID: 'DISCOVERY_FILTER_INVALID',
  NEARBY_NOT_OPTED_IN: 'DISCOVERY_NEARBY_NOT_OPTED_IN',
  NEARBY_LOCATION_MISSING: 'DISCOVERY_NEARBY_LOCATION_MISSING',
  NEARBY_RATE_LIMITED: 'DISCOVERY_NEARBY_RATE_LIMITED',
  NEARBY_CURSOR_INVALID: 'DISCOVERY_NEARBY_CURSOR_INVALID',
  LOCATION_INVALID: 'DISCOVERY_LOCATION_INVALID',
} as const;
