/** Mã lỗi của Matching module (docs/05 § 5.5). */
export const MatchingErrors = {
  TICKET_ALREADY_QUEUED: 'MATCHING_TICKET_ALREADY_QUEUED',
  TICKET_NOT_FOUND: 'MATCHING_TICKET_NOT_FOUND',
  TICKET_NOT_QUEUED: 'MATCHING_TICKET_NOT_QUEUED',
  TICKET_NOT_MATCHED: 'MATCHING_TICKET_NOT_MATCHED',
  TICKET_FORBIDDEN: 'MATCHING_TICKET_FORBIDDEN',
  TICKET_ALREADY_PRIORITY: 'MATCHING_TICKET_ALREADY_PRIORITY',
  CRITERIA_INVALID: 'MATCHING_CRITERIA_INVALID',
  PROFILE_INCOMPLETE: 'MATCHING_PROFILE_INCOMPLETE',
  SPEEDUP_RATE_LIMITED: 'MATCHING_SPEEDUP_RATE_LIMITED',
  IDEMPOTENCY_KEY_MISSING: 'MATCHING_IDEMPOTENCY_KEY_MISSING',
  IDEMPOTENCY_CONFLICT: 'MATCHING_IDEMPOTENCY_CONFLICT',
  GUEST_DAILY_LIMIT: 'MATCHING_GUEST_DAILY_LIMIT',
  GUEST_SPEEDUP_FORBIDDEN: 'MATCHING_GUEST_SPEEDUP_FORBIDDEN',
} as const;
