/** Mã lỗi của module short-video (docs/05 § 5.5). */
export const ShortVideoErrors = {
  VIDEO_UPLOAD_DISABLED: 'SHORT_VIDEO_UPLOAD_DISABLED',
  VIDEO_NOT_FOUND: 'SHORT_VIDEO_NOT_FOUND',
  VIDEO_FORBIDDEN: 'SHORT_VIDEO_FORBIDDEN',
  VIDEO_INVALID_TRANSITION: 'SHORT_VIDEO_INVALID_TRANSITION',
  VIDEO_UPLOAD_IDEMPOTENCY_CONFLICT: 'SHORT_VIDEO_UPLOAD_IDEMPOTENCY_CONFLICT',
  CAPTION_TOO_LONG: 'SHORT_VIDEO_CAPTION_TOO_LONG',
  CURSOR_INVALID: 'SHORT_VIDEO_CURSOR_INVALID',
} as const;
