/** Mã lỗi của Feed module (docs/05 § 5.5). */
export const FeedErrors = {
  POST_NOT_FOUND: 'FEED_POST_NOT_FOUND',
  COMMENT_NOT_FOUND: 'FEED_COMMENT_NOT_FOUND',
  POST_CONTENT_REQUIRED: 'FEED_POST_CONTENT_REQUIRED',
  GUEST_FORBIDDEN: 'FEED_GUEST_FORBIDDEN',
  CURSOR_INVALID: 'FEED_CURSOR_INVALID',
  POST_IDEMPOTENCY_CONFLICT: 'FEED_POST_IDEMPOTENCY_CONFLICT',
  STORY_NOT_FOUND: 'FEED_STORY_NOT_FOUND',
  STORY_MEDIA_URL_REQUIRED: 'FEED_STORY_MEDIA_URL_REQUIRED',
  STORY_REPLY_REQUIRES_FRIENDSHIP: 'FEED_STORY_REPLY_REQUIRES_FRIENDSHIP',
} as const;
