/** Mã lỗi của Feed module (docs/05 § 5.5). */
export const FeedErrors = {
  POST_NOT_FOUND: 'FEED_POST_NOT_FOUND',
  COMMENT_NOT_FOUND: 'FEED_COMMENT_NOT_FOUND',
  POST_CONTENT_REQUIRED: 'FEED_POST_CONTENT_REQUIRED',
  GUEST_FORBIDDEN: 'FEED_GUEST_FORBIDDEN',
  CURSOR_INVALID: 'FEED_CURSOR_INVALID',
} as const;
