export const SupportErrors = {
  CURSOR_INVALID: 'SUPPORT_CURSOR_INVALID',
  TICKET_NOT_FOUND: 'SUPPORT_TICKET_NOT_FOUND',
  IDEMPOTENCY_CONFLICT: 'SUPPORT_IDEMPOTENCY_CONFLICT',
  INVALID_TRANSITION: 'SUPPORT_INVALID_TRANSITION',
} as const;
